### ISSUE TITLE
Warning: `convert(::Type{Vector{Char}}, s::AbstractString)` is deprecated, use `Vector{Char}(s)` instead.

### ISSUE THREAD

**Issue by scls19fr** [JuliaIO/LibSerialPort.jl#23]
https://github.com/andrewadare/LibSerialPort.jl/blob/61674ec9a8054b46f02fa8a6a2688c7743ef3feb/src/high-level-api.jl#L374

**Comment by mgkuhn** [comment]
Fixed: the troublesome `readuntil` methods are now gone in release `v0.5.0` and you can instead use the `readuntil` methods from `Base` with `SerialPort`.
