### ISSUE TITLE
Publish a release

### ISSUE THREAD

**Issue by scls19fr** [JuliaIO/LibSerialPort.jl#27]
Hello,

maybe you should consider publishing a release.
https://github.com/attobot/attobot could help.

Kind regards

**Comment by scls19fr** [comment]
Hi @andrewadare
Publishing this package could be very useful. Any news about this?

**Comment by andrewadare** [comment]
Agreed, I have put this off long enough. I will work on publishing this package today.

**Comment by scls19fr** [comment]
According to https://discourse.julialang.org/t/switching-package-registration-systems-on-monday/22677
Switching package registration systems on Monday

using [Registrator](https://github.com/JuliaComputing/Registrator.jl) instead of attobot will be required

**Comment by scls19fr** [comment]
Thanks @andrewadare for publishing this 0.2.0 release
https://github.com/JuliaIO/LibSerialPort.jl/releases/tag/v0.2.0
