### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by scls19fr** [JuliaIO/LibSerialPort.jl#30]
Hi,

Following https://github.com/JuliaIO/Roadmap/issues/3#issuecomment-477745240

https://travis-ci.com/JuliaIO/LibSerialPort.jl

should be enabled

and https://github.com/JuliaIO/LibSerialPort.jl/blame/master/README.md#L1 should be changed

Kind regards

**Comment by andrewadare** [comment]
Thanks @samuelpowell for setting up Travis here. I don't have time ATM, but I think we need to set the right udev rules for permission to access the tty on linux.

**Comment by samuelpowell** [comment]
Okay, perhaps fixed in #32 - both Linux and MacOS now fail with the same errors. Is this better than before or have I broken something further?

**Comment by samuelpowell** [comment]
Fixed in #32
