### ISSUE TITLE
Build issues on OS X

### ISSUE THREAD

**Issue by yakir12** [JuliaIO/LibSerialPort.jl#44]
I've used this package to build a simple GUI controlling a LED strip from an Arduino for our lab (see code [here](https://github.com/yakir12/SolarLEDs.jl)). Everything works fine, except for one user who has `Mojave 10.14.3`. She does not have the usual build-tools installed on her machine to `] build LibSerialPort`. Apart from [googling](https://apple.stackexchange.com/a/339015) solutions, is there a nifty way to take care of such issues, or did I miss some simple trick?

I realize and recognize that this does not have to do with LibSerialPort specifically.

**Comment by andrewadare** [comment]
It sounds like the PR #43 will provide a nice solution, but that's for Julia 1.3+.

In the meantime, is it feasible to cross-compile for her architecture (e.g. from another machine with the same OS) and copy the artifacts to her machine? This is speculative...I have never tried it myself.

**Comment by yakir12** [comment]
Moving her to Julia 1.3 might not be outside the realms of possibilities... I'll try to see if we can explore that...

I considered just giving her the binaries, but I can't find any online, nor do I have access to a similar computer... 

Thanks for the feedback!

**Comment by ianshmean** [comment]
Moving to 1.3 would likely be the easiest (assuming the 1.3 release goes smoothly) but there could be a way to use the cross-compiled artifacts in `libserialport_jll` to make a pre-1.3 compliant BinaryProvider-based version, with a build.jl file.

**Comment by ianshmean** [comment]
I guess we can close this with #43 being merged and released
