### ISSUE TITLE
Array versions of write() don't work

### ISSUE THREAD

**Issue by mgkuhn** [JuliaIO/LibSerialPort.jl#50]
How to reproduce problem:
```julia
using LibSerialPort
dev= "/dev/ttyS0"
s = LibSerialPort.open_serial_port(dev, 115200)
write(s, ['@'])
```
This results in
```
ERROR: MethodError: no method matching sp_nonblocking_write(::Ptr{LibSerialPort.SPPort}, ::Array{Char,1})
Closest candidates are:
  sp_nonblocking_write(::Ref{LibSerialPort.SPPort}, ::Array{UInt8,N} where N) at ~/.julia/packages/LibSerialPort/xvkkM/src/wrap.jl:634
  sp_nonblocking_write(::Ref{LibSerialPort.SPPort}, ::Ptr{UInt8}) at ~/.julia/packages/LibSerialPort/xvkkM/src/wrap.jl:641
  sp_nonblocking_write(::Ref{LibSerialPort.SPPort}, ::String) at ~/.julia/packages/LibSerialPort/xvkkM/src/wrap.jl:648
```

Shouldn't the type signatures
```julia
write(sp::SerialPort, data::Array{Char})
write(sp::SerialPort, data::Array{UInt8})
```
really be
```julia
write(sp::SerialPort, data::Vector{Char})
write(sp::SerialPort, data::Vector{UInt8})
```
and likewise for `sp_nonblocking_write()`?

These functions seem not covered by the tests.

**Comment by mgkuhn** [comment]
Looking into this further, I think we should remove all implementations of `write()` methods from `high-level-api.jl`, as they now in a number of cases very much contradict the expected behaviour of `write()` in Base. Instead, there should only the two basic `write(sp::SerialPort, b::UInt8)` and `unsafe_write(sp::SerialPort, p::Ptr{UInt8}, nb::UInt)` expected by `base/io.jl` be implemented, and then `SerialPort` will inherit from `IO` all the same `write()`, `print()`, etc. output methods that Julia users are familiar with from file I/O.

I'm working on a PR.

**Comment by andrewadare** [comment]
A PR for this would be most welcome.

**Comment by mgkuhn** [comment]
PR #56 to fix this is now ready
