### ISSUE TITLE
Cannot open a Linux device via a symbolic link

### ISSUE THREAD

**Issue by mgkuhn** [JuliaIO/LibSerialPort.jl#63]
As Linux assigns the digits in `/dev/ttyUSB0`, `/dev/ttyUSB1`, etc. dynamically, it can be very useful to instead open a serial-port device via the symbolic links with more persistent names that Linux offers in `/dev/serial/by-id/` or `/dev/serial/by-path/`, e.g.
```
$ ls -l /dev/serial/by-id/
[...] usb-Digilent_Digilent_USB_Device_210321A6A8A3-if00-port0 -> ../../ttyUSB1
[...] usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 -> ../../ttyUSB0
```
Unfortunately, it seems `sp_get_port_by_name()` does not like symbolic links (on Ubuntu Linux 18.04 x86_64, Julia 1.4.1):
```
$ julia test/test-high-level-api.jl /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 115200
ERROR: LoadError: libserialport returned SP_ERR_ARG - Function was called with invalid arguments.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] check(::SPReturn) at /home/mgk25/.julia/dev/LibSerialPort/src/wrap.jl:138
 [3] sp_get_port_by_name at /home/mgk25/.julia/dev/LibSerialPort/src/wrap.jl:144 [inlined]
 [4] SerialPort(::String) at /home/mgk25/.julia/dev/LibSerialPort/src/high-level-api.jl:23
 [5] open(::String, ::Int64; mode::SPMode, ndatabits::Int64, parity::SPParity, nstopbits::Int64) at /home/mgk25/.julia/dev/LibSerialPort/src/high-level-api.jl:277
 [6] open at /home/mgk25/.julia/dev/LibSerialPort/src/high-level-api.jl:277 [inlined]
```

Looking at the C function `sp_get_port_by_name()` in [serialport.c](https://sigrok.org/gitweb/?p=libserialport.git;a=blob;f=serialport.c;h=51fe0788fc4abd015adc9768d63c9288ac9e0593;hb=HEAD), that does appear to call `realpath()` to resolve symlinks, but only if the flag `HAVE_REALPATH` is set.

So I now wonder whether `HAVE_REALPATH` wasn't set when the version of libserialport that I got was compiled.

`LibSerialPort/Project.toml` contains the lines
```
[deps]
libserialport_jll = "220460dc-b50e-5ed0-8176-09b0fd261e90"
[compat]
libserialport_jll = "0.1.1"
```
and I don't have the Ubuntu 18.04 package `libserialport0` installed, so I'm probably using a JLL “artifact”, right? (Installing the Ubuntu 18.04 package `libserialport0` made no difference either.)

It appears so:
```
$ nm ~/.julia/artifacts/939cdd32e306775f4c57d49341082a747bb8b561/lib/libserialport.so | grep real
                 U realloc@@GLIBC_2.2.5
$
```

**Comment by laborg** [comment]
Hi @mgkuhn
the underlying libserialport_jll has been updated and now contains this commit: https://github.com/sigrokproject/libserialport/commit/95bad38c5b073f8e44e525de3846e5538373eb10 which should make symlinks usable. Does this solve your problem?

**Comment by mgkuhn** [comment]
Problem disappeared after upgrade to libserialport_jll v0.1.2+0. Thanks @laborg !
