### ISSUE TITLE
Release 0.4?

### ISSUE THREAD

**Issue by ianshmean** [JuliaIO/LibSerialPort.jl#70]
0.4 has sat on master since we stalled the release https://github.com/JuliaRegistries/General/pull/5939

There have been a number of beneficial changes since, so it would be good to put out a release.

Also, with #61 upcoming, it would be good to get a stable release before that merges

cc. @andrewadare @mgkuhn @samuelpowell

**Comment by samuelpowell** [comment]
@ianshmean can you remind me why we stopped that registration?

@andrewadare any objections to releasing 0.4, I'm happy to do it.

**Comment by andrewadare** [comment]
I do not have any objections to releasing version 0.4. I also think we should get #61 merged and make a release from that. That PR has sat without approval for a long time, but it is ready to be merged.

**Comment by ianshmean** [comment]
The issue was this: https://github.com/JuliaIO/LibSerialPort.jl/pull/45#issuecomment-559243165

So we're ok with releasing 0.4 on the current master? And let's get #61 pushed out quickly after

**Comment by mgkuhn** [comment]
#61 still needs to [fix the default flow-control settings](https://github.com/JuliaIO/LibSerialPort.jl/pull/61#issuecomment-617108607), such that the binary-transparency tests also pass on e.g. Ubuntu Linux (where XON/XOFF is active by default). But feel free to merge #61 into master and I'll then quickly follow up with PRs for that, and perhaps also for restoring the timeout functionality.

**Comment by samuelpowell** [comment]
Okay, I'll do a release of 0.4, merge #61 and open an issue linking the comment above pending PR and then potentially 0.5

**Comment by ianshmean** [comment]
Just beat you to it @samuelpowell. I registered current master as 0.4 https://github.com/JuliaIO/LibSerialPort.jl/commit/801de822476adf44ecb9977f23d3f8bb66e620fe#commitcomment-41470735

**Comment by samuelpowell** [comment]
Cross post - I also asked for registration, both requests link to the same PR on registry so it appears the outcome is okay. I will open issue about #61 now.

**Comment by samuelpowell** [comment]
0.4 released, hopefully tagbot will tag shortly, will merge #61 to master
