### ISSUE TITLE
Fix default flow control settings post #61

### ISSUE THREAD

**Issue by samuelpowell** [JuliaIO/LibSerialPort.jl#72]
As per discussion https://github.com/JuliaIO/LibSerialPort.jl/issues/70#issuecomment-674103337, following a release of 0.4 the large changes implemented in #61 will be merged, at which point a PR to address https://github.com/JuliaIO/LibSerialPort.jl/pull/61#issuecomment-656229681 can be submitted by @mgkuhn prior to any cleanup on testing, etc., and release of 0.5.

Further:

- [x] Bump testing targets
- [x] Bump tagbot configuration to latest revision

**Comment by mgkuhn** [comment]
Fixed in ef40f3b which is part of PR #74.
