### ISSUE TITLE
"Inappropriate ioctl for device" when opening Port

### ISSUE THREAD

**Issue by mchristianl** [JuliaIO/LibSerialPort.jl#84]
Hi alltogether,

I am experimenting with LibSerialPort.jl, got it working a few weeks ago ... and suddenly it stopped working with the mentioned error message from the title :thinking:

I.e. with

• LibSerialPort `v0.5.0`
• Julia `v1.6.1`
• x64 Archlinux with kernel `v5.12.7`

when trying

```julia
using LibSerialPort
sp = LibSerialPort.open("/dev/ttyUSB0", 115200)
```

then, I receive the following error:

```julia
@0x00005596f79cfc40, SP_MODE_READ_WRITE)
OS error code 25: Inappropriate ioctl for device
ERROR: libserialport returned SP_ERR_FAIL - Host OS reported a failure.
Stacktrace:
 [1] check(ret::LibSerialPort.Lib.SPReturn)
   @ LibSerialPort.Lib ~/.julia/packages/LibSerialPort/zyrgR/src/wrap.jl:299
 [2] sp_open(port::Ptr{LibSerialPort.Lib.SPPort}, mode::SPMode)
   @ LibSerialPort.Lib ~/.julia/packages/LibSerialPort/zyrgR/src/wrap.jl:342
 [3] open(portname::String, baudrate::Int64; mode::SPMode, ndatabits::Int64, parity::SPParity, nstopbits::Int64)
   @ LibSerialPort ~/.julia/packages/LibSerialPort/zyrgR/src/LibSerialPort.jl:463
 [4] open(portname::String, baudrate::Int64)
   @ LibSerialPort ~/.julia/packages/LibSerialPort/zyrgR/src/LibSerialPort.jl:462
 [5] top-level scope
   @ REPL[2]:1
```

However: the serial device is responsive with `screen` and with other programs

```bash
screen /dev/ttyUSB0 115200
```

This might not be directly related to LibSerialPort.jl but I would appreciate any advice for debugging this issue

kind regards,
Christian

**Comment by mchristianl** [comment]
adapted from [an example of the libserialport documentation](https://sigrok.org/api/libserialport/unstable/a00046.html), I found that the _equivalent_ C-program

```c
#include <stdio.h>
#include <stdlib.h>
#include <libserialport.h>

int check(enum sp_return result);
int main(int argc, char ** argv){
  const char * portname = "/dev/ttyUSB0";
  int baudrate  = 115200;
  int mode      = SP_MODE_READ_WRITE;
  int ndatabits = 8;
  int parity    = SP_PARITY_NONE;
  int nstopbits = 1;
  struct sp_port *port;

  check(sp_get_port_by_name(portname, &port));
  check(sp_open(port, mode));

  return 0;
}
 
/* Helper function for error handling. */
int check(enum sp_return result)
{
  switch (result) {
    case SP_ERR_ARG:
      printf("Error: Invalid argument.\n");
      abort();
    case SP_ERR_FAIL:
      error_message = sp_last_error_message();
      printf("Error: Failed: %s\n", error_message);
      sp_free_error_message(error_message);
      abort();
    case SP_ERR_SUPP:
      printf("Error: Not supported.\n");
      abort();
    case SP_ERR_MEM:
      printf("Error: Couldn't allocate memory.\n");
      abort();
    case SP_OK:
    default:
      return result;
  }
}
```

when compiled with

```bash
gcc libserialport.c -lserialport -o libserialport
```

already leads to the _same_ result

```
Error: Failed: Inappropriate ioctl for device
```

so that seems to be an issue with libserialport already.

**Comment by mchristianl** [comment]
Okay, the issue was [already discovered](https://sigrok.org/bugzilla/show_bug.cgi?id=1687) and _"is fixed in the development version of libserialport"_ which I can confirm.

Installing `libserialport-git` (Archlinux, AUR) and linking
```bash
ln -sf /usr/lib/libserialport.so.0.1.0 ~/.julia/artifacts/ea89abffd87d072e6c6735b59759a5905ebddbed/lib
```
temporarily fixes the issue.

**Comment by mgkuhn** [comment]
Is it possible that Julia was the second process trying to open your `/dev/ttyUSB0` and the (5 years old?) `libserialport-0.1.1` version in the JLL lacks [this recent commit that switches to exclusive opening](https://sigrok.org/gitweb/?p=libserialport.git;a=commitdiff;h=ffbfc5c76ba8100d21d0141478a6c0d761ecfb2f)?


I noticed that Yggdrasill has already [a newer libserialport-0.1.2](https://github.com/JuliaPackaging/Yggdrasil/commit/4707965dab4f673eb3d0dbd130a8491d889e2e93#diff-d85b3342ad6f0165ebafdbeb490857efc6c9007c09bc6f3ae1b79f5f2c92dd43) that includes that fix, but [LibSerialPort.jl/Project.toml](https://github.com/JuliaIO/LibSerialPort.jl/blob/master/Project.toml) still refers to release 0.1.1.

**Comment by mchristianl** [comment]
> Is it possible that Julia was the second process trying to open your /dev/ttyUSB0 ?

I am pretty sure that this is not the case (using `lsof`, reattaching the USB and even rebooting did not change the error).

> I noticed that Yggdrasill has already a newer libserialport-0.1.2 that includes that fix

Thank you for investigating!

Removing the Archlinux-version which is downloaded from `git://sigrok.org/libserialport`

> commit 1b011060df5579c15bd4e103c2d8afc4d442fd72
> Tue Sep 22 03:10:08 2020 +0000

and switching to the Julia-development-version with `dev LibSerialPort` 

```julia
(@v1.6) pkg> activate LibSerialPort
  Activating environment at `~/.julia/dev/LibSerialPort/Project.toml`

(LibSerialPort) pkg> status libserialport_jll
     Project LibSerialPort v0.5.0
      Status `~/.julia/dev/LibSerialPort/Project.toml`
  [220460dc] libserialport_jll v0.1.2+0
```

does not seem to work for me and leads to the previous error, again .. even though this one from `https://github.com/sigrokproject/libserialport.git` should lead to the same download

> commit 1b011060df5579c15bd4e103c2d8afc4d442fd72
> Tue Sep 22 03:10:08 2020 +0000

So switching to the development version _should_ work in theory.

Might it be possible to just update the `Project.toml` in that case?

**Comment by karlp** [comment]
I've pasted a patch for libserialport on https://sigrok.org/bugzilla/show_bug.cgi?id=1687 that might help, this "works in development version" message was rather unclear...

**Comment by mgkuhn** [comment]
Thanks. Please let us know here when libserialport fixed this issue in a new release, and then we will update our dependencies here to a JLL based on that new release.

**Comment by karlp** [comment]
That won't be me at least sorry, I just found _this_ ticket while trying to solve the problem myself, I'm just another end user :)

**Comment by laborg** [comment]
@mgkuhn The dependency definition of LibSerialPort sees `0.1.2` as compatible with `0.1.1` so `libserialport_jll` is already available in the version that apparently should contain the fix.
```
(@v1.6) pkg> activate --temp
  Activating new environment at `/tmp/jl_NHj58q/Project.toml`

(jl_NHj58q) pkg> add LibSerialPort
    Updating registry at `~/.julia/registries/ActibeltRegistry`
    Updating git-repo `git@bitbucket.org:triumteam/act-jl-registry.git`
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
    Updating `/tmp/jl_NHj58q/Project.toml`
  [a05a14c7] + LibSerialPort v0.5.0
    Updating `/tmp/jl_NHj58q/Manifest.toml`
  [a05a14c7] + LibSerialPort v0.5.0
  [220460dc] + libserialport_jll v0.1.2+0
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
...
```
But this version isn't a remedy against the bug. At least not on my system (Ubuntu 21.04, Linux kernel  5.11.0-22). Replacing libserialport  with a new build as described by @mchristianl didn't work for me either. 

The only thing that helps is to *patch libserialport with the patch of @karlp  from https://sigrok.org/bugzilla/show_bug.cgi?id=1687 and replace the libserialport artifact.  Following the linked discussion I'm wondering if the recipe in BinaryBuilder should incorporate the patch...

**Comment by tlnagy** [comment]
Thanks everyone, applying @karlp's patch like @laborg fixed the ioctl errors that I started to get after I updated to Ubuntu 21.04. Here's what I did to get it to work:

```
git clone git@github.com:sigrokproject/libserialport.git

cd libserialport

# make @karlp edit to configure.ac

./autogen.sh
./configure
make
sudo make install
ln -sf /usr/local/lib/libserialport.so.0.1.0 "$(find ~/.julia/artifacts -name libserialport.so.0.1.0)"
```

and then Julia successfully connects to my serial device!

**Comment by laborg** [comment]
Upstream has added @karlp patch (https://github.com/sigrokproject/libserialport/commit/6f9b03e597ea7200eb616a4e410add3dd1690cb1) so we can use a new build to fix this issue.
