### ISSUE TITLE
Please enable CI build of documentation

### ISSUE THREAD

**Issue by mgkuhn** [JuliaIO/LibSerialPort.jl#86]
In commit 75d6ddc844 (part of PR #74) I added a CI build target for documentation formatted by [Documenter.jl](https://juliadocs.github.io/Documenter.jl/stable). Could you please [complete the steps](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/) needed to host this documentation on GitHub pages (setting up the SSH key, check again that everything is still in line with the latest conventions), and then add to the README.md the customary shields:

[![](https://img.shields.io/badge/docs-stable-blue.svg)](https://JuliaIO.github.io/LibSerialPort.jl/stable) [![](https://img.shields.io/badge/docs-dev-blue.svg)](https://JuliaIO.github.io/LibSerialPort.jl/dev)

(Alternatively, if you allow me to join the [JuliaIO](https://github.com/JuliaIO) organization, I'd also be delighted to finish this myself.)

**Comment by IanButterworth** [comment]
> Alternatively, if you allow me to join the JuliaIO organization, I'd also be delighted to finish this myself.

Sorry, I stalled on this when it was brought up before. I just invited you! 

The love this package needs has been on my mind for a while. Appreciate the help!

**Comment by mgkuhn** [comment]
@IanButterworth Thanks. Having accepted the invite appears to have enabled me now to close issues and merge PRs, but it still doesn't give me access to the “Settings” tab of this repo, which I need to use to [install SSH deploy keys](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh).

Also, does JuliaIO have any preference whether to use Travis CI or GitHub Actions to deploy gh-pages documentation? I'd quite like to deploy documentation for tagged versions, which I believe requires using the route [GitHub Actions](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions) with [SSH authentication](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Authentication:-SSH-Deploy-Keys), also for Tag Bot. (It's all become a bit complex since I last did this.)

**Comment by IanButterworth** [comment]
Ah yes, I just elevated your perms for this repo.

Travis CI for free projects isn't really an option anymore. I'd go with GitHub Actions.

**Comment by mgkuhn** [comment]
@IanButterworth Thanks, gh-pages documentation via GitHub Actions is now live at https://JuliaIO.github.io/LibSerialPort.jl/dev (“stable” should follow automatically at the next tagged release)
