### ISSUE TITLE
Can't set some port parameters before opening the port

### ISSUE THREAD

**Issue by Octogonapus** [JuliaIO/LibSerialPort.jl#95]
We have a need to set the DTR parameter before opening the serial port, but it seems this is not possible:
```julia
sp = LibSerialPort.SerialPort("/dev/ttyUSB0")
LibSerialPort.sp_set_dtr(sp.ref, LibSerialPort.SP_DTR_OFF)
ERROR: libserialport returned SP_ERR_ARG - Function was called with invalid arguments.
```

Is this a libserialport limitation, or a LibSerialPort.jl limitation?

**Comment by mgkuhn** [comment]
Can you explain your need in more detail? What exact difference does it make to you (on the serial-port wires) if you set DTR before or after opening the port?

**Comment by Octogonapus** [comment]
The DTR pin on our FTDI chip connects to our AVR's RESET pin, so if we can't select the DTR setting before opening the serial port, then the AVR will always be reset. We want to have control over when we reset the AVR, so we need to set the DTR before opening the serial port.

**Comment by mgkuhn** [comment]
Looking at [serialport.c](http://sigrok.org/gitweb/?p=libserialport.git;a=blob;f=serialport.c;h=e6097eeda975f914ec7b960f72c9e2df546e8281;hb=HEAD#l2347) it seems that `sp_set_dtr()` calls `CHECK_OPEN_PORT()` to check if there is a file descriptor open, and it seems that can only be passed after `sp_open()`, which in turn does not take any flow-control configuration parameters.

So, as far as I can see (from just looking for a couple of minutes), there may be no obvious way to do what you want via the [libserialport](http://sigrok.org/wiki/Libserialport) C library API. I don't see immediately a way how the Julia wrapper could mitigate that.

In case you don't need the cross-plattform (Linux/Windows/macOS) portability of libserialport, and you only work on e.g. Linux, I'd suggest you try using the [ioctl_tty(2)](https://man7.org/linux/man-pages/man2/ioctl_tty.2.html) API directly. (I don't know of anyone already maintaining a Linux `<termios.h>` wrapper for Julia.)

**Comment by Octogonapus** [comment]
Good eye. I agree this is an upstream issue.
